### ISSUE TITLE
help

### ISSUE THREAD

**Issue by haleylovesroses** [FredyH/GWSockets#10]
Hello. We are trying to install this on pterodactyl panel for gmod and it keeps giving this error
error loading module 'gwsockets' from file 'gmsv_gwsockets_linux.dll':
    /lib/i386-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/container/garrysmod/lua/bin/gmsv_gwsockets_linux.dll)

maybe you could help out? The panel runs in docker containers.

**Comment by FredyH** [comment]
It appears I compiled it with a version of glibc that was way too high and thus most people cannot use the linux version.
I'll compile it using an older version this weekend, for now you can just use the previous version of the library and it should work.

**Comment by FredyH** [comment]
I just recompiled it, can you test if it works for you now?

**Comment by haleylovesroses** [comment]
Hello. I tried your version and received this error. https://media.discordapp.net/attachments/425847787062820864/630602249835380736/Screenshot_2019-10-06-20-08-00.png?width=280&height=559

I ended up having one of my other developers recompile it on the same machine as the host and it works fine.

**Comment by FredyH** [comment]
This should not be an issue anymore, it is now compiled under Ubuntu 16.04 and should therefore work with most systems.
