### ISSUE TITLE
SSL Error (Incompatible with Discord Integration?)

### ISSUE THREAD

**Issue by Chillstice** [FredyH/GWSockets#13]
For context I've been using [this Discord Integration addon](https://www.gmodstore.com/market/view/trixter-s-discord-integration) for months now.

Edit: I should probably mention this is on linux

When using an old version of GWSockets the addon works great, but when trying to use the new 1.1.0 version (from August) it throws an SSL error:

Discord -> Getting auth token...
Discord -> Trying to use websocket to connect to the backend...
Discord -> GWSockets is successfully installed!
Discord -> WebSocket errored: Unable to find matching SSL root certificate locally.
Discord -> WebSocket disconnected.

The whole Discord integration fails and is unresponsive.

This happens with both the 32 and 64 bit versions. I don't understand what SSL cert it's looking for nor whether or not it's required for GWSockets or the Discord integration. If I use the old version there are no issues. This is the only error I can find.

If you have any questions or need any other information, don't hesitate to reply.

**Comment by Chillstice** [comment]
Trixter already replied to my ticket and said: 

> Hi,
> Chances are this is caused by https://github.com/FredyH/GWSockets/pull/11 but I can't help with this as I don't maintain the module. You can either report this issue through the github issues (with the Unable to find matching SSL root certificate locally message) or just uninstall the module to fallback to HTTP.

**Comment by FredyH** [comment]
I am not sure what this is caused by yet, it seems like libssl fails to find the root certificates so I am going to have to debug it in a standalone application.

**Comment by FredyH** [comment]
I fixed it, check out the new 1.1.1 release.
If it still doesn't work please reopen this issue.
