### ISSUE TITLE
Connection not establishing

### ISSUE THREAD

**Issue by Mattzi** [FredyH/GWSockets#17]
Hello,

I currently have the issue that the connection to the server is never completing even though sv_hibernate_think is set to 1 and the server is showing the connection happening. But no Functions are calles and isConnected returns false.
Any Suggestions?

**Comment by sammyt291** [comment]
Are you able to publish or link your connection code or part of, so people can check the structure?
Im having no problems with it on Windows, would love to help if I can

**Comment by Mattzi** [comment]
Ok i tested it using your tool there and it seems to be a Server-Side Problem. On the side of my Nodejs Socket Server. Anybody has experience there and can tell me how they are handling connects to get it to work?

**Comment by sammyt291** [comment]
I also use Node for my server,
using the 'ws' library I always build my project starting with their "Simple server" example on their GitHub: https://github.com/websockets/ws

the example right under that is a great start if you intend to use WSS with SSL certs :)
Hope those help if you have not been there yet

**Comment by Mattzi** [comment]
Well I tried to work with net.Socket because I have confirmed it working with gmod_luasocket. For another Project I wanted to try an better updated library

**Comment by FredyH** [comment]
gmod_luasocket provides normal TCP sockets though, right? Because GWSocket offers WebSockets only and require specific support from the server.

**Comment by Mattzi** [comment]
That fixed it. Thank you
