### ISSUE TITLE
Again this error, pls help

### ISSUE THREAD

**Issue by PrikolMen** [FredyH/GWSockets#18]
Discord -> GWSockets is successfully installed!
Discord -> WebSocket errored: Unable to find matching SSL root certificate locally.
Discord -> WebSocket disconnected.

**Comment by FredyH** [comment]
What OS are you on and what version of GWSockets are you using?

**Comment by PrikolMen** [comment]
Centos 8

**Comment by FredyH** [comment]
It might be that the libssl that I linked does not have the correct path for the certificates in Centos. You could try instead using Ubuntu/Debian/Fedora to see if it works there, or alternatively compile the library using Centos' libssl.

**Comment by PrikolMen** [comment]
I cannot change the server operating system, discord integration on the server requires your library

**Comment by PrikolMen** [comment]
OpenSSL installed on my system

**Comment by FredyH** [comment]
Yes compile the library yourself on centos using the compile instructions, but instead use the libssl of your OS.
