### ISSUE TITLE
GWSockets not working on Crident

### ISSUE THREAD

**Issue by konsolekonnect** [FredyH/GWSockets#19]
I am unable to use your modules on crident. It wont require it properly. 
https://i.imgur.com/eOUADo2.png
https://i.imgur.com/FvJrqbD.png

**Comment by FredyH** [comment]
Contact your server host and ask why it doesn't work.

**Comment by konsolekonnect** [comment]
Contacted  crident. 
They sent me this.
https://i.imgur.com/aImwbks.png
yet the module still says its missing
https://i.imgur.com/w437Ozj.png

**Comment by FredyH** [comment]
CentOS' glibc is too outdated for this module. CentOS 6's version is 10 years old now and I am not going to support it.

Either ask your host to update the version for you or compile the module yourself.
