### ISSUE TITLE
Can't require gwsockets

### ISSUE THREAD

**Issue by marceltransier** [FredyH/GWSockets#2]
First of all: Thanks for this great work!

My problem:
I can't require gwsockets.
I only get "[ERROR]" in the console.

I'm running it on Debian 8 and I placed the .dll file in the garrysmod/lua/bin directory.

Do you have an idea how to fix this?

**Comment by FredyH** [comment]
That's weird, have you tried requiring the dll on windows (in gmod), does at least that work?

**Comment by TrixterTheTux** [comment]
Receiving this too on Ubuntu 16.04. Requiring the module again works (or at least the global table GWSockets exists). Tried the 0.9 version, exactly same issue.

**Comment by FredyH** [comment]
So it works after requiring it twice?
Are you running any special gamemode?
Is this after changing map or first time you start the server?

**Comment by TrixterTheTux** [comment]
Yes, it works after second require.
The error happens on darkrp + sandbox (which are the only ones I've tested)
Both scenarios cause the error, and in both cases 2nd require fixes it.

**Comment by FredyH** [comment]
Hmm, that's really weird, I just tested it on Ubuntu 18.04 and it worked just fine running sandbox. Is your server up-to-date?

**Comment by TrixterTheTux** [comment]
In terms of dependencies, everything is up to date. The only difference is, that I'm running 16.04 compared to 18.04. If you want, I can give you access to the server which is having this issue (though it's on Crident's game panel, and can't give SSH for obvious reasons). It's probably easier to do this through Discord if you want to, Trixter#0001.

**Comment by KGoodale13** [comment]
We use this on our server running Ubuntu 16.04 and it works fine. You must be missing a dependency or something
