### ISSUE TITLE
How fix this shit

### ISSUE THREAD

**Issue by PrikolMen** [FredyH/GWSockets#24]
I buy Trixter's Discord Integration, install last version gwsockets...
Discord -> Reconnecting with WebSocket...
Discord -> WebSocket errored: Unable to find matching SSL root certificate locally.
Discord -> WebSocket disconnected.

**Comment by FredyH** [comment]
Try setting the correct root verify paths using WSockets.addVerifyPath( "/etc/ssl/certs" ).
Also please refrain from being so rude when you want to be helped for free, or you will end up with no one helping you.

**Comment by PrikolMen** [comment]
ok
