### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by JurisBog** [FredyH/GWSockets#25]
Is this ready to go on a live server? If not, where can I help?

**Comment by viral32111** [comment]
What makes you feel this *isn't* ready for production use?

**Comment by JurisBog** [comment]
I am just making sure. :) I am glad to see that it is good to rock'n'roll!

**Comment by FredyH** [comment]
I'm currently not aware of any major bugs and GWSockets is actively being used on larger servers.
