### ISSUE TITLE
Socket not connecting, even with example code

### ISSUE THREAD

**Issue by reesercollins** [FredyH/GWSockets#26]
I seem to be having issues with GWSockets where my sockets aren't connecting, even running the provided example code with no other addons.

OS: Windows 10
GWSockets Version: Latest 32bit
GMod Version: Latest

Not sure what other information you need, since it's all provided code.

**Comment by FredyH** [comment]
Do you have a player on the server? Otherwise the callbacks are not called.

**Comment by reesercollins** [comment]
No. Can't seem to find that information anywhere in the documentation. Is there anyway to disable that?

**Comment by FredyH** [comment]
You can use the convar sv_hibernate_think to also have callbacks called when there are no clients connected.
