### ISSUE TITLE
Issue under Rocky Linux release 8.4 (Green Obsidian)

### ISSUE THREAD

**Issue by Jindego** [FredyH/GWSockets#28]
Discord -> Reconnecting with WebSocket...
Discord -> WebSocket errored: Unable to find matching SSL root certificate locally.
Discord -> WebSocket disconnected.

**Comment by FredyH** [comment]
Some Linux distros choose other paths for their root certificates than the one used by default in gwsockets.
You can add the correct path using:
```LUA
 GWSockets.addVerifyPath( "/etc/ssl/certs" )
```
Note: The actual path used by Rocky Linux might be different than the one above, you will have to look it up.

**Comment by Jindego** [comment]
Checked that dir, currently have the following
[root@192 certs]# pwd
/etc/ssl/certs
[root@192 certs]# ls -ltr
total 4
lrwxrwxrwx. 1 root root   55 Sep 21 14:33 ca-bundle.trust.crt -> /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
lrwxrwxrwx. 1 root root   49 Sep 21 14:33 ca-bundle.crt -> /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
-rw-r--r--. 1 root root 2171 Nov 12 10:12 postfix.pem

Is it the case I’m missing some?

**Comment by Jindego** [comment]
Or is the path different by default?
