### ISSUE TITLE
Example does not work visibly 

### ISSUE THREAD

**Issue by arouke** [FredyH/GWSockets#29]
Hello,
I wanted to test websockets on gmod, so I just took the example. I put it on the server side and run it.
Here is its answer: 
Error: Connection failed: A connection attempt failed because the connected party did not respond properly after a certain period of time or an established connection failed because the connecting host did not respond (Basically, it was in French since I am French, I don't know if that helps?)
I wonder if it came from my fire but no.
Thank you.

**Comment by FredyH** [comment]
It looks like the the echo server does not exist anymore. Could you try swapping out the URL for `https://echo.websocket.events/`? That one might work.

**Comment by arouke** [comment]
That was it, it works perfectly.
Can you update the readme?
