### ISSUE TITLE
Windows release seems to be outdated

### ISSUE THREAD

**Issue by TrixterTheTux** [FredyH/GWSockets#3]
Hi,

By the looks of it, the Windows 1.0.0 release is outdated. After requiring the module the update checker keeps telling me that the current version is outdated, yet I'm sure that I've downloaded the 1.0.0 version which should be the latest. The same thing doesn't happen on Linux version of the module.

**Comment by FredyH** [comment]
You seem to be right, I recompiled it and now it should be the correct version. If not just let me know.
