### ISSUE TITLE
Could it be that the websocket can only be 1 at a time ?

### ISSUE THREAD

**Issue by Pdzly** [FredyH/GWSockets#31]
So for example Server 1 Has the same port and address used and server 2 the same

**Comment by FredyH** [comment]
Could you be more specific? There should be no restrictions with being able to connect to the same server twice at the same time.

**Comment by viral32111** [comment]
Are you asking if you can have multiple servers listen on the same address and port combination? If so, that's impossible. The port number must not conflict with any other listening sockets. Though listening as a websocket server is outside the scope of this module afaik.
