### ISSUE TITLE
[Win Server 2019] Couldn't load module library! (%1 is not a valid Win32 application.)

### ISSUE THREAD

**Issue by CheezusChrust** [FredyH/GWSockets#32]
I am currently unable to load the module as when I require it on my server I get this error.
![u6vIPvg](https://user-images.githubusercontent.com/21130637/193628075-09ef10f1-ff86-49d1-b2f0-51e2b4f6d274.png)
I have tested the latest release, and tried building it myself. I am on the latest non-beta SRCDS (32 bit), running on Windows Server 2019. Visual C++ Redistributable 2017 was installed from the link provided in the description of the project.

**Comment by FredyH** [comment]
Did you get this specific error when trying to run the version you compiled yourself?
If so, then something likely went incredibly wrong during that process, like compiling it as something other than a DLL.

What error do you get when you require the precompiled one?

You might be missing the 32-bit version of the C++ Redistributable, they do offer a 32 and 64-bit version.

**Comment by CheezusChrust** [comment]
Oh yep it was my fault, I installed the 64-bit version rather than the 32-bit, it's working now. Thanks!
