### ISSUE TITLE
Linux Server Crashing on x64

### ISSUE THREAD

**Issue by Pawsative** [FredyH/GWSockets#35]
Hi there,

I'm getting random crashes using GWSockets on Linux x64, not sure if we're using too many connections or sending too much data at once time, I've attached some logs below if it will help. It seems to be random, and I can't find a cause for it to replicate the issue.

![image](https://github.com/FredyH/GWSockets/assets/8021703/41300c8d-6bbd-4acb-93a5-57b976e549b9)
![image](https://github.com/FredyH/GWSockets/assets/8021703/4ff2cbd9-714e-4497-9819-8f24863bfcf6)
[2c5e2543-8a0a-43f2-945c8188-236a429b.dmp](https://github.com/FredyH/GWSockets/files/13268672/2c5e2543-8a0a-43f2-945c8188-236a429b.dmp)
[e9dacc4f-dce6-4446-d0a979bc-dba2c5de.dmp](https://github.com/FredyH/GWSockets/files/13268673/e9dacc4f-dce6-4446-d0a979bc-dba2c5de.dmp)

If you need any more information, please feel free to reach out.

**Comment by FredyH** [comment]
It should only really crash if you are sending way too much data so that the ram is full.

How many websocket connections do you have? Just one or multiple.
Also, do you open connections a lot, or only when the server loads up.

Maybe there is also a stack-trace of where exactly the crash happened in your debug.log file.

**Comment by Pawsative** [comment]
There's only one connection open as far as I'm aware, the only thing that uses GWSockets for us is Squish Logs (https://github.com/SquishLogs/gmod-integration)

Unfortunately, the crashes doesn't seem to be generating a debug.log, but it is making the memory dumps

**Comment by FredyH** [comment]
Do you run the server with the `-debug` flag?
If not, please add it and see if it writes an entry in the debug.log then. Having the stack trace of the crash would be extremely helpful.

**Comment by Pawsative** [comment]
Yeah, both my servers are using the -debug flag, Squish just pushed an update that prevents it from spam attempting to reconnect if it disconnects, I'll try that and let you know if that was the issue.
