### ISSUE TITLE
Library does not work, no error message, no anything.

### ISSUE THREAD

**Issue by GoldenStarGamer** [FredyH/GWSockets#36]
By running the example written on README.md nothing gets run and nothing displays any errors.

**Comment by FredyH** [comment]
You need to have a player on the server for it to work.

**Comment by GoldenStarGamer** [comment]
> You need to have a player on the server for it to work.

i am running a local singleplayer game, maybe it's that?

**Comment by GoldenStarGamer** [comment]
I tried running on a Local Server with max 2 players, ran like a breeze

**Comment by GoldenStarGamer** [comment]
I tried running on a Local Server with max 2 players, ran like a breeze

**Comment by cristian-spiescu** [comment]
I don't think single player vs multi player is the issue. But in single player, when you open the console, it somehow freezes the server. So you need to close the console and let the server run a bit, and then look at the console again.

In multi player, opening the console, doesn't freeze the server.

I'm wondering if there is some kind of console command that toggles this behavior for single player as well.
