### ISSUE TITLE
Disconnecting after 30-60s

### ISSUE THREAD

**Issue by Zoom-Developer** [FredyH/GWSockets#39]
After connecting my websocket disconnecting after +- 30-60s, with server all correct, why that can happened?

```lua
w.connect = function()
        w.ws = GWSockets.createWebSocket(url)

        function w.ws:onMessage(msg)
            w.onMessage(msg)
        end
        function w.ws:onConnected()
            w.connected = true
            w.onConnected()
        end
        function w.ws:onDisconnected()
            w.connected = false
            w.onDisconnected()
        end

        w.ws:open()
    end
```

**Comment by FredyH** [comment]
You likely have to keep the connection alive by sending any message every 30 seconds, otherwise the server thinks your socket has disconnected.

**Comment by Zoom-Developer** [comment]
Strange, the server doesnt need a keepalive messages, but if I write "echo" every 15s, connection doesnt terminating...
