### ISSUE TITLE
Cannot use Clientside even after changing module name

### ISSUE THREAD

**Issue by Lordalpha001** [FredyH/GWSockets#40]
I'm using 64 bit for gmod and i needed client side for something I was working on and when I change the module name and then try to use my Lua in my server I get an error on my require("gwsockets")

**Comment by FredyH** [comment]
Does it work under 32 bit? Also, did you rename the module so that it can be loaded on the client?
What is the error?

**Comment by Lordalpha001** [comment]
i renamed it and it didnt work so it tried 32 bit and i still got the same errors
[ERROR] Couldn't include file 'includes\modules\gwsockets.lua' - File not found or is empty (@[C] (line 1))
  1. unknown - [C]:1
  
  
  [ERROR] [C]:1: Module not found!
  1. require - [C]:-1
   2. unknown - [C]:1

also i need it for 64bit

**Comment by FredyH** [comment]
The correct name needs to be `gmcl_gwsockets_win64.dll`, make sure it is called that. The error indicates that it does not find the file.

**Comment by Lordalpha001** [comment]
yeah i just tried that and now i got a new error saying it couldnt load module library (%1 is not a valid Win32 application).

**Comment by Lordalpha001** [comment]
Yup got it to work now thank you!
