### ISSUE TITLE
Add to the readme that VC++ 2017 x86 redist is required.

### ISSUE THREAD

**Issue by TheKigen** [FredyH/GWSockets#5]
You should really add to the installation instructions that Visual Studio C++ 2017 x86 redist is required.

For those who need it, it is available at https://visualstudio.microsoft.com/downloads/ at the bottom of the page under Other Tools and Frameworks.

**Comment by FredyH** [comment]
Added it. It's a real shame microsoft can't get their own libraries to be available on their own operating system.

**Comment by TheKigen** [comment]
You have to set some flags at compile time to make your project not require the VC++ redists.  You can also avoid using the libraries that require what's contained in the redists.

**Comment by FredyH** [comment]
Hmm, presumably I can expect people using the library to use the redist since it is required by all sorts of software and I am not even sure we can just get rid of it.
